name: BlocksDS release
run-name: Build a full BlocksDS release

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  # Fetches all the sources and generates a source tarball
  build-source-tarball:
    runs-on: ubuntu-24.04
    outputs:
      sha8: ${{ steps.slug.outputs.sha8 }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install wget tar git
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Fetch sources
        run: |
          ./run.sh download
      - name: Upload source tarball
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: blocksds-source-${{ steps.slug.outputs.sha8 }}
          path: |
            download/*
            patches/*
            Makefile
            run.sh
            debian/*
            fedora-specs/*

  # Builds the toolchain for ubuntu and generates a binary tarball
  build-binary-ubuntu:
    runs-on: ubuntu-24.04
    needs:
      - build-source-tarball
    steps:
      - name: Install dependencies
        run: sudo apt-get install curl libgmp-dev libmpfr-dev libmpc-dev bison xz-utils make tar ninja-build libisl-dev meson texinfo bzip2 doxygen
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Fetch source tarball artifact
        uses: actions/download-artifact@v4
        with:
          name: blocksds-source-${{ needs.build-source-tarball.outputs.sha8 }}
          path: ./
      - name: Build from source tarball
        run: |
          make
          cd toolchain && tar -cf ../blocksds-ubuntu-24.04-${{ steps.slug.outputs.sha8 }}.tar .
      - name: Upload binary release tarball
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: blocksds-ubuntu-24.04-${{ steps.slug.outputs.sha8 }}.tar
          path: blocksds-ubuntu-24.04-${{ steps.slug.outputs.sha8 }}.tar

  # Create release
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs:
      - build-source-tarball
      - build-binary-ubuntu
    steps:
      - name: Get release version
        id: tagversion
        if: startsWith(github.ref, 'refs/tags/')
        run: fullref="${{ github.ref }}"; tagversion=${fullref#"refs/tags/"}; echo "tagversion=${tagversion}" >> $GITHUB_OUTPUT
      - name: Fetch source assets
        uses: actions/download-artifact@v4
        with:
          name: blocksds-source-${{ needs.build-source-tarball.outputs.sha8 }}
          path: ./src
      - name: Fetch binary assets
        uses: actions/download-artifact@v4
        with:
          name: blocksds-ubuntu-24.04-${{ needs.build-source-tarball.outputs.sha8 }}.tar
          path: ./bin-ubuntu-24.04
      - name: Package assets
        run: |
          tar -czf blocksds-source-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz -C ./src .
          tar -czf blocksds-ubuntu-24.04-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz -C ./bin-ubuntu-24.04 .
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (source)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: blocksds-source-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz
          asset_name: blocksds-source-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz
          asset_content_type: application/octet-stream
      - name: Upload Release Asset (Ubuntu 24.04 binaries)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: blocksds-ubuntu-24.04-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz
          asset_name: blocksds-ubuntu-24.04-${{ steps.tagversion.outputs.tagversion }}-${{ needs.build-source-tarball.outputs.sha8 }}.tar.gz
          asset_content_type: application/octet-stream

